const BLOGS = [
  {
    id: 1,
    image: "/images/blog1.jpg",
    category: "Technology",
    title: "Learn How AI is Shaping the World",
    date: "Dec 1, 2023",
    duration: 10,
  },
  {
    id: 2,
    image: "/images/blog2.jpg",
    category: "Productivity",
    title: "Top 10 Tools for Remote Work",
    date: "Nov 25, 2023",
    duration: 8,
  },
  {
    id: 3,
    image: "/images/blog3.jpg",
    category: "Programming",
    title: "Understanding JavaScript Closures",
    date: "Nov 20, 2023",
    duration: 12,
  },
  {
    id: 4,
    image: "/images/blog4.jpg",
    category: "Lifestyle",
    title: "Healthy Habits for Developers",
    date: "Nov 18, 2023",
    duration: 7,
  },
  {
    id: 5,
    image: "/images/blog5.jpg",
    category: "Design",
    title: "UI/UX Trends for 2024",
    date: "Nov 15, 2023",
    duration: 15,
  },
  {
    id: 6,
    image: "/images/blog6.jpg",
    category: "Education",
    title: "Learning React for Beginners",
    date: "Nov 10, 2023",
    duration: 6,
  },
  {
    id: 7,
    image: "/images/blog7.jpg",
    category: "Data Science",
    title: "Introduction to Machine Learning",
    date: "Nov 5, 2023",
    duration: 10,
  },
  {
    id: 8,
    image: "/images/blog8.jpg",
    category: "Technology",
    title: "Is Blockchain the Future?",
    date: "Nov 1, 2023",
    duration: 14,
  },
  {
    id: 9,
    image: "/images/blog9.jpg",
    category: "Career",
    title: "How to Grow as a Software Engineer",
    date: "Oct 30, 2023",
    duration: 9,
  },
];

export default BLOGS;
